---
- name: Create temp directory
  win_file:
    path: C:\temp
    state: directory

- name: Install Chocolatey
  win_chocolatey:
    name: chocolatey
    state: present

- name: Install common tools via Chocolatey
  win_chocolatey:
    name:
      - curl
      - wget
      - 7zip
      - git
      - googlechrome
      - notepadplusplus
    state: present

- name: Check if AWS CLI is installed
  win_command: aws --version
  register: aws_cli_check_win
  failed_when: false
  changed_when: false

- name: Install AWS CLI
  win_chocolatey:
    name: awscli
    state: present
  when: aws_cli_check_win.rc != 0

- name: Install Docker Desktop
  win_chocolatey:
    name: docker-desktop
    state: present

- name: Disable Windows Server Manager auto-start
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\ServerManager
    name: DoNotOpenServerManagerAtLogon
    data: 1
    type: dword

- name: Disable IE Enhanced Security Configuration for Administrators
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}
    name: IsInstalled
    data: 0
    type: dword

- name: Disable IE Enhanced Security Configuration for Users
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}
    name: IsInstalled
    data: 0
    type: dword

- name: Install Tailscale
  win_chocolatey:
    name: tailscale
    state: present

- name: Download and install Prometheus Windows Exporter
  block:
    - name: Download Windows Exporter
      win_get_url:
        url: "https://github.com/prometheus-community/windows_exporter/releases/download/v0.24.0/windows_exporter-0.24.0-amd64.msi"
        dest: "C:\temp\windows_exporter.msi"
    - name: Install Windows Exporter
      win_package:
        path: "C:\temp\windows_exporter.msi"
        state: present
