---
- name: Get GitHub Personal Access Token from AWS Secrets Manager
  set_fact:
    github_access_token: "{{ lookup('aws_secret', github_token_secret, region=aws_region) | from_json | json_query('token') }}"

- name: Get terraform-heezy registration token
  uri:
    url: "https://api.github.com/repos/{{ terraform_repo }}/actions/runners/registration-token"
    headers:
      Authorization: "token {{ github_access_token }}"
      Accept: "application/vnd.github.v3+json"
    method: POST
    status_code: 201
  register: terraform_registration
  delegate_to: localhost
  become: false
  run_once: true

- name: Get ansible-heezy registration token
  uri:
    url: "https://api.github.com/repos/{{ ansible_repo }}/actions/runners/registration-token"
    headers:
      Authorization: "token {{ github_access_token }}"
      Accept: "application/vnd.github.v3+json"
    method: POST
    status_code: 201
  register: ansible_registration
  delegate_to: localhost
  become: false
  run_once: true