---
- name: Check if Docker is installed
  command: which docker
  register: docker_check
  failed_when: false
  changed_when: false

- name: Install Docker
  block:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
  when: docker_check.rc != 0

- name: Check if user is in docker group
  command: groups {{ github_runner_user }}
  register: user_groups
  changed_when: false

- name: Add user to docker group
  user:
    name: "{{ github_runner_user }}"
    groups: docker
    append: yes
  when: "'docker' not in user_groups.stdout"

- name: Refresh docker group membership
  shell: newgrp docker
  become: yes
  become_user: "{{ github_runner_user }}"
  when: "'docker' not in user_groups.stdout"
  ignore_errors: yes