---
- name: Check if GitHub CLI is installed
  command: which gh
  register: gh_check
  failed_when: false
  changed_when: false

- name: Install GitHub CLI
  block:
    - name: Add GitHub CLI GPG key
      apt_key:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg
        state: present
    - name: Add GitHub CLI repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        state: present
    - name: Install GitHub CLI
      apt:
        name: gh
        state: present
        update_cache: yes
  when: gh_check.rc != 0

- name: Create actions-runner directories
  file:
    path: "/home/{{ github_runner_user }}/actions-runner-{{ item.0.name }}-{{ item.1 }}"
    state: directory
    mode: '0755'
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_user }}"
  loop: "{{ runner_repos | product(range(1, runners_per_repo + 1)) | list }}"

- name: Check if GitHub Actions runner is downloaded
  stat:
    path: /tmp/actions-runner.tar.gz
  register: runner_archive

- name: Download GitHub Actions runner
  get_url:
    url: "https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/actions-runner-linux-x64-{{ github_runner_version }}.tar.gz"
    dest: "/tmp/actions-runner.tar.gz"
  when: not runner_archive.stat.exists

- name: Check if runners are configured
  stat:
    path: "/home/{{ github_runner_user }}/actions-runner-{{ item.0.name }}-{{ item.1 }}/.runner"
  register: runners_configured
  loop: "{{ runner_repos | product(range(1, runners_per_repo + 1)) | list }}"

- name: Extract GitHub Actions runner
  unarchive:
    src: "/tmp/actions-runner.tar.gz"
    dest: "/home/{{ github_runner_user }}/actions-runner-{{ item.item.0.name }}-{{ item.item.1 }}"
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_user }}"
    remote_src: yes
  when: not item.stat.exists
  loop: "{{ runners_configured.results }}"

- name: Set permissions on runner directories
  file:
    path: "/home/{{ github_runner_user }}/actions-runner-{{ item.item.0.name }}-{{ item.item.1 }}"
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_user }}"
    mode: '0755'
    recurse: yes
  when: not item.stat.exists
  loop: "{{ runners_configured.results }}"

- name: Configure runners
  command: >
    ./config.sh --url https://github.com/{{ item.item.0.repo }}
    --token {{ terraform_registration.json.token if item.item.0.name == 'terraform' else ansible_registration.json.token }}
    --name heezy-{{ hostname }}-{{ item.item.0.name }}-{{ item.item.1 }}
    --labels {{ item.item.0.labels }}
    --unattended
  args:
    chdir: "/home/{{ github_runner_user }}/actions-runner-{{ item.item.0.name }}-{{ item.item.1 }}"
  become: yes
  become_user: "{{ github_runner_user }}"
  when: not item.stat.exists
  loop: "{{ runners_configured.results }}"

- name: Install runner services
  command: ./svc.sh install
  args:
    chdir: "/home/{{ github_runner_user }}/actions-runner-{{ item.item.0.name }}-{{ item.item.1 }}"
  when: not item.stat.exists
  loop: "{{ runners_configured.results }}"

- name: Start runner services
  command: ./svc.sh start
  args:
    chdir: "/home/{{ github_runner_user }}/actions-runner-{{ item.0.name }}-{{ item.1 }}"
  loop: "{{ runner_repos | product(range(1, runners_per_repo + 1)) | list }}"
