repos:
  - repo: local
    hooks:
      - id: generate-workflows
        name: Generate GitHub Workflows
        entry: scripts/generate-workflows.py
        language: python
        additional_dependencies: [PyYAML>=6.0]
        files: ^(inventory/hosts\.yml|playbooks/.*\.yml|roles/.*/.*|scripts/generate-workflows\.py)$
        pass_filenames: false
        stages: [manual]