repos:
  - repo: local
    hooks:
      - id: generate-workflows
        name: Generate GitHub Workflows
        entry: scripts/generate-workflows.py
        language: python
        additional_dependencies: [PyYAML>=6.0]
        files: ^(playbooks/.*\.yml)$
        pass_filenames: false