---
all:
  children:
    github-runner:
      hosts:
        192.168.200.2:
          hostname: github-runner
    
    pxe:
      hosts:
        192.168.1.28:
          hostname: shared-pxe
    
    dnsmasq:
      hosts:
        192.168.1.29:
          hostname: shared-dnsmasq
    
    lgtm:
      hosts:
        192.168.1.10:
          hostname: shared-lgtm
    
    linux:
      children:
        github-runner:
        pxe:
        dnsmasq:
        lgtm:
    
    windows:
      hosts: {}
      # 192.168.1.32:
      #   hostname: windows-vm
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_port: 5985
        ansible_winrm_scheme: http
        ansible_winrm_connection_timeout: 60
        ansible_become: no
        ansible_user: "{{ lookup('aws_secret', 'production/heezy/windows/administrator/credentials', region='us-east-2') | from_json | json_query('username') }}"
        ansible_password: "{{ lookup('aws_secret', 'production/heezy/windows/administrator/credentials', region='us-east-2') | from_json | json_query('password') }}"
  
  vars:
    ansible_user: "{{ lookup('aws_secret', 'production/heezy/ubuntu/cloud-init-credentials', region='us-east-2') | from_json | json_query('username') }}"
    ansible_password: "{{ lookup('aws_secret', 'production/heezy/ubuntu/cloud-init-credentials', region='us-east-2') | from_json | json_query('password') }}"
    ansible_become_password: "{{ lookup('aws_secret', 'production/heezy/ubuntu/cloud-init-credentials', region='us-east-2') | from_json | json_query('password') }}"
    dns_server: 192.168.1.29
    dns_domain: heezy.local