---
- name: Create minecraft directory
  file:
    path: /opt/minecraft
    state: directory
    mode: '0755'

- name: Create docker-compose file
  copy:
    content: |
      version: '3.8'
      services:
        minecraft:
          image: itzg/minecraft-bedrock-server:latest
          container_name: minecraft-bedrock
          environment:
            EULA: "TRUE"
            GAMEMODE: survival
            DIFFICULTY: easy
            SERVER_NAME: "Heezy Bedrock Server"
            MAX_PLAYERS: 10
            ALLOW_CHEATS: "false"
            ONLINE_MODE: "true"
          ports:
            - "19132:19132/udp"
          volumes:
            - ./data:/data
          restart: unless-stopped
    dest: /opt/minecraft/docker-compose.yml
    mode: '0644'

- name: Start Minecraft Bedrock server
  community.docker.docker_compose_v2:
    project_src: /opt/minecraft
    state: present

- name: Open firewall for Minecraft Bedrock
  ufw:
    rule: allow
    port: '19132'
    proto: udp