---
- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ prometheus_config_path }}"
    - "{{ prometheus_data_path }}"

- name: Create Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    mode: '0644'
  notify: restart prometheus

- name: Create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/prometheus/docker-compose.yml
    mode: '0644'
  notify: restart prometheus

- name: Start Prometheus container
  docker_compose:
    project_src: /opt/prometheus
    state: present