name: Setup AWS Credentials

on:
  workflow_call:
    inputs:
      runner-type:
        description: 'Runner type (ubuntu-latest or self-hosted)'
        required: true
        type: string
    outputs:
      runner-access-key:
        description: 'Runner AWS access key'
        value: ${{ jobs.setup.outputs.runner-access-key }}
      runner-secret-key:
        description: 'Runner AWS secret key'
        value: ${{ jobs.setup.outputs.runner-secret-key }}

jobs:
  setup:
    runs-on: ${{ inputs.runner-type }}
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    outputs:
      runner-access-key: ${{ steps.get-creds.outputs.access-key }}
      runner-secret-key: ${{ steps.get-creds.outputs.secret-key }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}:role/GitHubActions-MultiRepo
          aws-region: us-east-2

      - name: Login to ECR
        if: inputs.runner-type == 'self-hosted'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get runner credentials from AWS Secrets
        id: get-creds
        run: |
          CREDS=$(aws secretsmanager get-secret-value --secret-id production/heezy/github_runner/aws_credentials --query SecretString --output text)
          echo "access-key=$(echo $CREDS | jq -r '.AWS_ACCESS_KEY_ID')" >> $GITHUB_OUTPUT
          echo "secret-key=$(echo $CREDS | jq -r '.AWS_SECRET_ACCESS_KEY')" >> $GITHUB_OUTPUT