name: Ansible Provision

on:
  workflow_dispatch:
    inputs:
      target_hosts:
        description: 'Target hosts (comma-separated)'
        required: true
        type: string
      playbook:
        description: 'Playbook to run'
        required: true
        type: choice
        options:
          - baseline
          - prometheus
          - github-runner
          - tailscale
          - custom-role
        default: baseline
      custom_role:
        description: 'Custom role name (if playbook=custom-role)'
        required: false
        type: choice
        options:
          - minecraft-server
          - web-server

      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - prod
        default: prod

permissions:
  id-token: write
  contents: read

jobs:
  get-runner-credentials:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      runner-access-key: ${{ steps.get-creds.outputs.access-key }}
      runner-secret-key: ${{ steps.get-creds.outputs.secret-key }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}:role/GitHubActions-MultiRepo
          aws-region: us-east-2

      - name: Get runner credentials from AWS Secrets
        id: get-creds
        run: |
          CREDS=$(aws secretsmanager get-secret-value --secret-id production/heezy/github_runner/aws_credentials --query SecretString --output text)
          echo "access-key=$(echo $CREDS | jq -r '.AWS_ACCESS_KEY_ID')" >> $GITHUB_OUTPUT
          echo "secret-key=$(echo $CREDS | jq -r '.AWS_SECRET_ACCESS_KEY')" >> $GITHUB_OUTPUT

  provision:
    needs: get-runner-credentials
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      

      
      - name: Create dynamic inventory
        run: |
          mkdir -p inventory
          echo "[all]" > inventory/dynamic_hosts
          IFS=',' read -ra HOSTS <<< "${{ inputs.target_hosts }}"
          for host in "${HOSTS[@]}"; do
            echo "$host" >> inventory/dynamic_hosts
          done
          echo "" >> inventory/dynamic_hosts
          echo "[all:vars]" >> inventory/dynamic_hosts
          echo "ansible_user={{ lookup('aws_secret', 'production/heezy/ubuntu/cloud-init-credentials', region='us-east-2') | from_json | json_query('username') }}" >> inventory/dynamic_hosts
          echo "ansible_password={{ lookup('aws_secret', 'production/heezy/ubuntu/cloud-init-credentials', region='us-east-2') | from_json | json_query('password') }}" >> inventory/dynamic_hosts
          echo "ansible_become_password={{ lookup('aws_secret', 'production/heezy/ubuntu/cloud-init-credentials', region='us-east-2') | from_json | json_query('password') }}" >> inventory/dynamic_hosts
      
      - name: Run Ansible playbook
        run: |
          chmod +x .github/scripts/run-ansible.sh
          EXTRA_VARS=""
          if [ "${{ inputs.playbook }}" = "custom-role" ]; then
            EXTRA_VARS="CUSTOM_ROLE=${{ inputs.custom_role }}"
          fi
          .github/scripts/run-ansible.sh ${{ inputs.playbook }} inventory/dynamic_hosts "$EXTRA_VARS" ${{ needs.get-runner-credentials.outputs.runner-access-key }} ${{ needs.get-runner-credentials.outputs.runner-secret-key }} ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}
