name: Build and Push to ECR

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: build-ecr
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build-ecr.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit

  notify:
    if: always()
    needs: [build]
    uses: ./.github/workflows/_discord-notify.yml
    with:
      status: ${{ needs.build.result == 'success' && 'success' || 'failure' }}
      workflow-name: 'Build ECR'
    secrets: inherit