name: Build and Push to ECR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-ecr.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit