name: Commit Triggered Deployment

on:
  push:
    paths:
      - 'inventory/**'
      - 'roles/baseline/**'
      - 'roles/prometheus/**'
      - 'roles/github-runner/**'
      - 'playbooks/baseline.yml'
      - 'playbooks/prometheus.yml'
      - 'playbooks/github-runner.yml'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ansible-deployment
  cancel-in-progress: false

jobs:
  get-runner-credentials:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      runner-access-key: ${{ steps.get-creds.outputs.access-key }}
      runner-secret-key: ${{ steps.get-creds.outputs.secret-key }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}:role/GitHubActions-MultiRepo
          aws-region: us-east-2

      - name: Get runner credentials from AWS Secrets
        id: get-creds
        run: |
          CREDS=$(aws secretsmanager get-secret-value --secret-id production/heezy/github_runner/aws_credentials --query SecretString --output text)
          echo "access-key=$(echo $CREDS | jq -r '.AWS_ACCESS_KEY_ID')" >> $GITHUB_OUTPUT
          echo "secret-key=$(echo $CREDS | jq -r '.AWS_SECRET_ACCESS_KEY')" >> $GITHUB_OUTPUT

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      baseline: ${{ steps.changes.outputs.baseline }}
      prometheus: ${{ steps.changes.outputs.prometheus }}
      github-runner: ${{ steps.changes.outputs.github-runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            baseline:
              - 'inventory/**'
              - 'roles/baseline/**'
              - 'playbooks/baseline.yml'
            prometheus:
              - 'inventory/**'
              - 'roles/prometheus/**'
              - 'playbooks/prometheus.yml'
            github-runner:
              - 'inventory/**'
              - 'roles/github-runner/**'
              - 'playbooks/github-runner.yml'

  deploy:
    needs: [get-runner-credentials, detect-changes]
    runs-on: self-hosted
    timeout-minutes: 60
    strategy:
      matrix:
        playbook: [
          { name: "baseline", condition: "${{ needs.detect-changes.outputs.baseline == 'true' }}" },
          { name: "prometheus", condition: "${{ needs.detect-changes.outputs.prometheus == 'true' }}" },
          { name: "github-runner", condition: "${{ needs.detect-changes.outputs.github-runner == 'true' }}" }
        ]
      fail-fast: false
    if: ${{ matrix.playbook.condition }}
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.playbook.name }} playbook
        run: |
          chmod +x .github/scripts/run-ansible.sh
          .github/scripts/run-ansible.sh ${{ matrix.playbook.name }} inventory/hosts.heezy "" ${{ needs.get-runner-credentials.outputs.runner-access-key }} ${{ needs.get-runner-credentials.outputs.runner-secret-key }} ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}