name: Release Build

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-ecr.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit