name: Scheduled Maintenance

on:
  schedule:
    # Baseline: Weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'
    # Prometheus: Weekly on Saturdays at 3 AM UTC  
    - cron: '0 3 * * 6'
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Playbook to run'
        required: true
        type: choice
        options:
          - baseline
          - prometheus
        default: baseline

permissions:
  id-token: write
  contents: read

jobs:
  setup-aws:
    uses: ./.github/workflows/_setup-runner-aws-credentials.yml
    with:
      runner-type: ubuntu-latest
    secrets: inherit

  baseline:
    if: github.event.schedule == '0 3 * * 0' || github.event.inputs.playbook == 'baseline'
    needs: setup-aws
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      
      - name: Run baseline playbook
        run: |
          chmod +x .github/scripts/run-ansible.sh
          .github/scripts/run-ansible.sh baseline inventory/hosts.heezy "" ${{ needs.setup-aws.outputs.runner-access-key }} ${{ needs.setup-aws.outputs.runner-secret-key }} ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}

  prometheus:
    if: github.event.schedule == '0 3 * * 6' || github.event.inputs.playbook == 'prometheus'
    needs: setup-aws
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      
      - name: Run prometheus playbook
        run: |
          chmod +x .github/scripts/run-ansible.sh
          .github/scripts/run-ansible.sh prometheus inventory/hosts.heezy "" ${{ needs.setup-aws.outputs.runner-access-key }} ${{ needs.setup-aws.outputs.runner-secret-key }} ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}